### ISSUE TITLE
在服务器上使用时会调用服务器没有的函数导致报错

### ISSUE THREAD

**Issue by koaker** [ukmojb/ItemStagesPlus#1]
具体在itemstages.java中onLivingUpdate中final ItemStack stack = player.getItemStackFromSlot(slot).getItem().getDefaultInstance();这一句，服务器中并不存在getDefaultInstance()导致报错，现在勉强的解决方法是在服务器上的此模组全部识别为创造模式，即创建一个boolean类型，把创造模式的判断全部替换才能勉强运行，请修复这个bug，谢谢

**Comment by ukmojb** [comment]
emm.......这个模组早就被ut合并了))))))
用ut去
